FROM node:20-alpine

LABEL author="Server Argentina Tech" maintainer="danelsonic123@serverargentina.com"

RUN apk add --no-cache \
    ffmpeg \
    iproute2 \
    git \
    sqlite \
    sqlite-dev \
    python3 \
    py3-pip \
    tzdata \
    curl \
    bash \
    zip \
    tar \
    build-base \
    libtool \
    bind-tools \
    iputils

RUN adduser -D container

RUN npm install -g npm@latest pm2

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh
CMD ["/bin/sh", "/entrypoint.sh"]
